# Generated by Django 5.2.4 on 2025-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_birth",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date of birth"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/%Y/%m/%d/", verbose_name="Photo"
            ),
        ),
    ]
