# Generated by Django 5.2.4 on 2025-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_date_birth_alter_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="or_model",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
