# Generated by Django 5.2.4 on 2025-09-04 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_or_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="chat_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="eleven_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="or_model",
        ),
        migrations.CreateModel(
            name="ApiConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eleven_key", models.CharField(max_length=256)),
                ("chat_key", models.CharField(max_length=256)),
                ("or_model", models.CharField(blank=True, max_length=256)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
