# Generated by Django 5.2.4 on 2025-09-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_chat_key_remove_user_eleven_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconfig",
            name="eleven_key",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
