# Generated by Django 5.2.4 on 2025-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_apiconfig_eleven_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="persona_description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="persona_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=256,
                null=True,
                verbose_name="Persona name",
            ),
        ),
    ]
