# Generated by Django 5.2.7 on 2026-10-03 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DEFAULT_MODEL = "nousresearch/hermes-3-llama-3.1-405b"  # what the chat used when no model was set


def copy_keys_to_profiles(apps, schema_editor):
    """Turn each user's old OpenRouter key + model into a "Main" connection profile."""
    ApiConfig = apps.get_model("users", "ApiConfig")
    ConnectionProfile = apps.get_model("users", "ConnectionProfile")
    TaskSetting = apps.get_model("users", "TaskSetting")
    for config in ApiConfig.objects.exclude(chat_key=""):
        profile = ConnectionProfile.objects.create(
            user_id=config.user_id, name="Main", provider="openrouter",
            api_key=config.chat_key, model=config.or_model or DEFAULT_MODEL,
        )
        TaskSetting.objects.create(user_id=config.user_id, task="chat", profile=profile)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_persona_description_user_persona_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openrouter", "OpenRouter"),
                            ("openai_compatible", "OpenAI-compatible (custom URL)"),
                        ],
                        default="openrouter",
                        max_length=32,
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        help_text="Only for custom providers",
                        max_length=512,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=512)),
                ("model", models.CharField(max_length=256)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["time_create"],
            },
        ),
        migrations.CreateModel(
            name="TaskSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=32)),
                ("model", models.CharField(blank=True, max_length=256)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual only")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=10, help_text="Run every N messages (automatic mode)"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="users.connectionprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="connectionprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_profile_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasksetting",
            constraint=models.UniqueConstraint(
                fields=("user", "task"), name="unique_task_per_user"
            ),
        ),
        migrations.RunPython(copy_keys_to_profiles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="apiconfig",
            name="chat_key",
        ),
        migrations.RemoveField(
            model_name="apiconfig",
            name="or_model",
        ),
    ]
