# Generated by Django 5.2.4 on 2025-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadsFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
        migrations.RemoveField(
            model_name="character",
            name="photo",
        ),
        migrations.AddField(
            model_name="character",
            name="photo_angry",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Angry emotion",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="photo_calm",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Calm emotion",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="photo_confused",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Confused emotion",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="photo_happy",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Happy emotion",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="photo_neutral",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Neutral emotion",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="photo_sad",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Sad emotion",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="photo_scared",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Scared emotion",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="photo_scheming",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Scheming emotion",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="photo_surprised",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Surprised emotion",
            ),
        ),
    ]
