# Generated by Django 5.2.4 on 2025-08-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_uploadsfiles_remove_character_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="worldbook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="characters",
                to="mainapp.worldbook",
            ),
        ),
    ]
