# Generated by Django 5.2.4 on 2025-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_alter_character_worldbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldbook",
            name="json_file",
            field=models.FileField(blank=True, null=True, upload_to="worldbooks_json/"),
        ),
    ]
