# Generated by Django 5.2.4 on 2025-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_chatsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="chat_log_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="chat_logs/%Y/%m/%d/",
                verbose_name="Chat log file",
            ),
        ),
    ]
