# Generated by Django 5.2.4 on 2025-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0007_alter_chatsettings_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("scenario", models.TextField(blank=True)),
                ("initial_message", models.TextField(blank=True)),
                (
                    "photo_neutral",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo_happy",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo_sad",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo_angry",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo_surprised",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo_scared",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo_confused",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo_calm",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo_scheming",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
