# Generated by Django 5.2.4 on 2025-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0008_charactertemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Default character"),
        ),
    ]
