# Generated by Django 5.2.4 on 2025-10-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0009_character_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="is_default",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Default character"
            ),
        ),
    ]
