# Generated by Django 5.2.7 on 2025-11-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_character_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='eleven_voice_char_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='eleven_voice_char_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='eleven_voice_narr_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='eleven_voice_narr_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
