# Generated by Django 5.2.7 on 2025-11-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_character_eleven_voice_char_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='eleven_voice_char_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='eleven_voice_narr_name',
        ),
    ]
