# Generated by Django 5.2.7 on 2025-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_character_eleven_voice_char_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_mult',
            field=models.BooleanField(default=False),
        ),
    ]
