# Generated by Django 5.2.7 on 2025-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_character_is_mult'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='photo_second_angry',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Angry emotion'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_calm',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Calm emotion'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_confused',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Confused emotion'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_happy',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Happy emotion'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_neutral',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Neutral emotion'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_sad',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Sad emotion'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_scared',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Scared emotion'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_scheming',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Scheming emotion'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_surprised',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Second character - Surprised emotion'),
        ),
        migrations.AlterField(
            model_name='character',
            name='photo_confused',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photosф/%Y/%m/%d/', verbose_name='Confused emotion'),
        ),
    ]
