# Generated by Django 5.2.7 on 2025-12-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_character_is_mult'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='photo_second_angry',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_calm',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_confused',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_happy',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_neutral',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_sad',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_scared',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_scheming',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo_second_surprised',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_mult',
            field=models.BooleanField(default=False, verbose_name='Multi-Character Mode'),
        ),
    ]
