# Generated by Django 5.2.7 on 2025-12-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_character_photo_second_angry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='eleven_voice_second_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='2nd Character Voice ID'),
        ),
    ]
