# Generated by Django 5.2.7 on 2026-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_character_eleven_voice_second_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="tracker_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
