# Generated by Django 5.2.7 on 2026-10-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0017_character_tracker_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsettings",
            name="samplers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
