# Generated by Django 5.2.7 on 2026-10-03 14:39

import django.db.models.deletion
from django.db import migrations, models


def existing_logs_to_chats(apps, schema_editor):
    """Each character's existing chat file becomes its "Chat 1"."""
    Character = apps.get_model("mainapp", "Character")
    Chat = apps.get_model("mainapp", "Chat")
    for character in Character.objects.exclude(chat_log_file="").exclude(chat_log_file__isnull=True):
        Chat.objects.create(character=character, title="Chat 1", log_file=character.chat_log_file.name)


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0019_presets"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Chat", max_length=200)),
                (
                    "log_file",
                    models.FileField(blank=True, null=True, upload_to="chat_logs/"),
                ),
                (
                    "branch_point",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Messages copied from the parent",
                        null=True,
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="mainapp.character",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branches",
                        to="mainapp.chat",
                    ),
                ),
            ],
            options={
                "ordering": ["-time_update"],
            },
        ),
        migrations.RunPython(existing_logs_to_chats, migrations.RunPython.noop),
    ]
