# Generated by Django 5.2.7 on 2026-10-04 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0020_chats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulbaSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="Model profile id the user will chat with",
                        max_length=64,
                    ),
                ),
                ("stage", models.CharField(default="extras", max_length=32)),
                (
                    "messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Conversation as sent to Bulba's model",
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        blank=True, default=list, help_text="What the page shows"
                    ),
                ),
                ("preferences", models.JSONField(blank=True, default=list)),
                ("proposals", models.JSONField(blank=True, default=list)),
                (
                    "spent",
                    models.FloatField(
                        default=0.0, help_text="USD, as reported by OpenRouter"
                    ),
                ),
                ("budget", models.FloatField(default=5.0, help_text="USD per session")),
                ("active", models.BooleanField(default=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulba_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-time_update"],
            },
        ),
    ]
