# Generated by Django 5.2.7 on 2026-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0021_bulba_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="alternate_greetings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="character",
            name="card_creator",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Card author"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="card_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="card_version",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Card version"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="example_dialogue",
            field=models.TextField(blank=True, verbose_name="Example dialogue"),
        ),
        migrations.AddField(
            model_name="character",
            name="personality",
            field=models.TextField(blank=True, verbose_name="Personality summary"),
        ),
        migrations.AddField(
            model_name="character",
            name="post_history_instructions",
            field=models.TextField(
                blank=True, verbose_name="Card's post-history instructions"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="system_prompt",
            field=models.TextField(blank=True, verbose_name="Card's system prompt"),
        ),
    ]
