# Generated by Django 5.2.7 on 2026-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0022_character_card_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsettings",
            name="appearance",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
