# Generated by Django 5.2.7 on 2026-10-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0023_chat_appearance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulbasession",
            name="activity",
            field=models.CharField(
                blank=True,
                help_text="What Bulba is doing right now, for the page",
                max_length=200,
            ),
        ),
    ]
