# Generated by Django 5.2.7 on 2026-10-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0024_bulba_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulbasession",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulba_sessions",
                to="mainapp.chat",
            ),
        ),
        migrations.AddField(
            model_name="bulbasession",
            name="mode",
            field=models.CharField(default="setup", max_length=16),
        ),
    ]
