# Generated by Django 5.2.7 on 2026-10-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0025_bulba_chat_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsettings",
            name="regex",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
