# Generated by Django 5.2.7 on 2026-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0027_preset_block_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="theme",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
