# Generated by Django 5.2.7 on 2026-10-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0028_character_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulbasession",
            name="focus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mainapp.character",
            ),
        ),
    ]
