# Generated by Django 5.2.7 on 2026-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0029_bulba_focus"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="voice_cast",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
