# Generated by Django 5.2.7 on 2026-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0030_character_voice_cast"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="watch",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="watch",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
